apiVersion: v1
kind: Service
metadata:
  name: vizario-staging-svc
  namespace: vizario-staging
  labels:
    app: fastapi     # ✅ label needed by ServiceMonitor
spec:
  selector:
    app: fastapi     # ✅ must match your deployment label
  ports:
    - name: http      # ✅ needed for ServiceMonitor to find the right port
      protocol: TCP
      port: 78
      targetPort: 8000
      nodePort: 32078
  type: NodePort

