apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: vizario-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: ghcr.io/daesung9511/mlops-pipeline-tandon:production
          ports:
            - containerPort: 8082

