apiVersion: v1
kind: Service
metadata:
  name: vizario-prod-svc
  namespace: vizario-prod
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80           # Service port
      targetPort: 80     # Must match containerPort
      nodePort: 32080    # Will be reachable via node1's floating IP
  type: NodePort

