apiVersion: v1
kind: Service
metadata:
  name: vizario-prod-svc
  namespace: vizario-prod
  metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80           # external-facing port inside cluster
      targetPort: 8000   # this must match containerPort
      nodePort: 32080    # exposed on node1's floating IP
  type: NodePort

